import type { Metadata } from "next";
import "./globals.css";
import { AeonikPro } from "@/font";
import { Manrope } from "next/font/google";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

const manrope = Manrope({
	weight: ["500"],
	subsets: ["latin"],
	variable: "--font-manrope",
});

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${AeonikPro.variable} ${manrope.variable} antialiased font-sans bg-primary-25`}
			>
				{children}
			</body>
		</html>
	);
}
